import { Campus, StudentProfile, Category, ExchangeSpot, Listing, NeedRequest, SemesterPackItem } from './types';

export const INITIAL_CAMPUSES: Campus[] = [
  {
    id: 'camp-iitd',
    name: 'Indian Institute of Technology Delhi',
    shortCode: 'IIT Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    domainSuffix: 'iitd.ac.in',
  },
  {
    id: 'camp-bits',
    name: 'BITS Pilani (Pilani Campus)',
    shortCode: 'BITS Pilani',
    city: 'Pilani',
    state: 'Rajasthan',
    domainSuffix: 'pilani.bits-pilani.ac.in',
  },
  {
    id: 'camp-nitt',
    name: 'National Institute of Technology Trichy',
    shortCode: 'NIT Trichy',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    domainSuffix: 'nitt.edu',
  },
];

export const INITIAL_PROFILES: Record<string, StudentProfile> = {
  'user-rahul': {
    id: 'user-rahul',
    campusId: 'camp-iitd',
    fullName: 'Rahul Sharma',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    collegeEmail: 'rahul.cs21@iitd.ac.in',
    isStudentVerified: true,
    degreeProgram: 'B.Tech Computer Science',
    currentYear: 4,
    currentSemester: 8,
    phoneNumber: '+91 98765 43210',
    upiId: 'rahul@okhdfcbank',
    totalTransactions: 9,
    successfulTransactions: 9,
    responseRatePercent: 96,
    avgResponseMinutes: 14,
    trustRating: 4.9,
    memberSinceYear: 2023,
  },
  'user-amit': {
    id: 'user-amit',
    campusId: 'camp-iitd',
    fullName: 'Amit Verma',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    collegeEmail: 'amit.me24@iitd.ac.in',
    isStudentVerified: true,
    degreeProgram: 'B.Tech Mechanical Engineering',
    currentYear: 1,
    currentSemester: 2,
    phoneNumber: '+91 98111 22334',
    upiId: 'amit.v@okicici',
    totalTransactions: 3,
    successfulTransactions: 3,
    responseRatePercent: 92,
    avgResponseMinutes: 20,
    trustRating: 4.8,
    memberSinceYear: 2024,
  },
  'user-priya': {
    id: 'user-priya',
    campusId: 'camp-iitd',
    fullName: 'Priya Sundaram',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200',
    collegeEmail: 'priya.ee23@iitd.ac.in',
    isStudentVerified: true,
    degreeProgram: 'B.Tech Electrical Engineering',
    currentYear: 2,
    currentSemester: 4,
    phoneNumber: '+91 97234 56789',
    upiId: 'priya.ee@paytm',
    totalTransactions: 6,
    successfulTransactions: 6,
    responseRatePercent: 100,
    avgResponseMinutes: 8,
    trustRating: 5.0,
    memberSinceYear: 2023,
  },
};

export const INITIAL_SPOTS: ExchangeSpot[] = [
  {
    id: 'spot-lib',
    campusId: 'camp-iitd',
    name: 'Central Library Foyer (Ground Floor)',
    description: 'CCTV monitored, safe & active until 9:00 PM',
    isRecommended: true,
  },
  {
    id: 'spot-sac',
    campusId: 'camp-iitd',
    name: 'Student Activity Center (SAC) Coffee Point',
    description: 'High footfall student hub, perfect during daylight hours',
    isRecommended: true,
  },
  {
    id: 'spot-gate',
    campusId: 'camp-iitd',
    name: 'Academic Gate 2 Guard Desk',
    description: 'Open 24/7 with campus security guards present',
    isRecommended: true,
  },
  {
    id: 'spot-canteen',
    campusId: 'camp-iitd',
    name: 'Himadri/Nilgiri Hostel Common Hall',
    description: 'Hostel quadrangle exchange point for evening drop-offs',
    isRecommended: false,
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-calc',
    slug: 'calculators',
    name: 'Scientific Calculators',
    icon: 'Calculator',
    description: 'Casio FX-991CW, FX-991EX, graphic & financial models',
    displayOrder: 1,
  },
  {
    id: 'cat-draw',
    slug: 'drawing-kits',
    name: 'Engineering Drawing Kits',
    icon: 'DraftingCompass',
    description: 'Mini drafters, compass kits, sheet containers & T-squares',
    displayOrder: 2,
  },
  {
    id: 'cat-books',
    slug: 'textbooks',
    name: 'Course Textbooks',
    icon: 'BookOpen',
    description: 'Engineering math, physics, coding, gate & competitive exams',
    displayOrder: 3,
  },
  {
    id: 'cat-coats',
    slug: 'lab-coats',
    name: 'Lab Coats & Practical Kits',
    icon: 'FlaskConical',
    description: 'White cotton lab coats, dissection kits, breadboard kits',
    displayOrder: 4,
  },
  {
    id: 'cat-elec',
    slug: 'electronics',
    name: 'Electronics & Hardware',
    icon: 'Cpu',
    description: 'Arduino kits, sensors, monitors, cables & accessories',
    displayOrder: 5,
  },
  {
    id: 'cat-packs',
    slug: 'bundles',
    name: 'Semester Starter Packs',
    icon: 'Package',
    description: 'Curated semester packs from seniors: all-in-one saving bundles',
    displayOrder: 6,
  },
];

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'list-casio-cw',
    sellerId: 'user-rahul',
    campusId: 'camp-iitd',
    categoryId: 'cat-calc',
    title: 'Casio FX-991CW ClassWiz Scientific Calculator',
    description: 'Used for Sem 1-4 engineering math and stats. Clean LCD, responsive keypad with natural textbook display. Protective snap-on hard case included.',
    images: [
      'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'BUY',
    price: 750,
    originalNewPrice: 1595,
    condition: 'EXCELLENT',
    targetCourse: 'Engineering',
    relevantSemesters: [1, 2, 3, 4],
    status: 'ACTIVE',
    preferredSpotId: 'spot-lib',
    viewsCount: 42,
    savesCount: 11,
    createdAt: '2026-10-06T10:30:00Z',
  },
  {
    id: 'list-drafter-kit',
    sellerId: 'user-rahul',
    campusId: 'camp-iitd',
    categoryId: 'cat-draw',
    title: 'Omega Engineering Mini Drafter + Drawing Board Sheet Holder',
    description: 'Complete Engineering Graphics & Design set. Stainless steel clamps, unbroken scale with 360-degree protractor head. Plastic carry tube included.',
    images: [
      'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'BUY',
    price: 450,
    originalNewPrice: 1150,
    condition: 'GOOD',
    targetCourse: 'Mechanical / Civil / Common Eng',
    relevantSemesters: [1, 2],
    status: 'ACTIVE',
    preferredSpotId: 'spot-sac',
    viewsCount: 29,
    savesCount: 7,
    createdAt: '2026-10-05T14:15:00Z',
  },
  {
    id: 'list-kreyszig-math',
    sellerId: 'user-priya',
    campusId: 'camp-iitd',
    categoryId: 'cat-books',
    title: 'Advanced Engineering Mathematics by Erwin Kreyszig (10th Edition)',
    description: 'Essential textbook for Semester 1 & 2 Mathematics. Complete binding, clear chapters, minimal pencil notations on only 3 pages. No missing pages.',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'EXCHANGE',
    price: 320,
    originalNewPrice: 899,
    exchangeDetails: 'Willing to exchange for Sem 3 Signals & Systems (Oppenheim) or ₹320 cash',
    condition: 'LIKE_NEW',
    bookInspection: {
      hasHighlighting: false,
      hasWriting: true,
      missingPages: false,
      coverWear: false,
      edition: '10th International Edition',
      isbn: '978-0470458365',
    },
    targetCourse: 'All Engineering Branches',
    relevantSemesters: [1, 2],
    status: 'ACTIVE',
    preferredSpotId: 'spot-lib',
    viewsCount: 38,
    savesCount: 9,
    createdAt: '2026-10-07T09:00:00Z',
  },
  {
    id: 'list-lab-coat',
    sellerId: 'user-priya',
    campusId: 'camp-iitd',
    categoryId: 'cat-coats',
    title: 'Pure Cotton Lab Coat (Unisex, Size M) + Safety Eyewear',
    description: 'Thick 100% white cotton coat mandatory for Chemistry & Workshop labs. Freshly washed, no chemical burns or tears.',
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'GIVE_AWAY',
    price: 0,
    originalNewPrice: 450,
    condition: 'GOOD',
    targetCourse: 'Common Engineering 1st Year',
    relevantSemesters: [1, 2],
    status: 'ACTIVE',
    preferredSpotId: 'spot-gate',
    viewsCount: 51,
    savesCount: 14,
    createdAt: '2026-10-04T16:20:00Z',
  },
  {
    id: 'list-sem2-pack',
    sellerId: 'user-rahul',
    campusId: 'camp-iitd',
    categoryId: 'cat-packs',
    title: 'Semester 2 Engineering All-In-One Starter Pack',
    description: 'Passing senior bundle: 1) Kreyszig Math, 2) Mini Drafter Kit, 3) Engineering Physics Book, 4) Breadboard + Jumpers kit. Clear your semester needs in one single campus pickup!',
    images: [
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'BUY',
    price: 1100,
    originalNewPrice: 2850,
    condition: 'EXCELLENT',
    isBundle: true,
    bundleItems: [
      'Erwin Kreyszig Math (10th Ed)',
      'Omega Mini Drafter & Board Clips',
      'Engineering Physics (Gaur & Gupta)',
      'Electronic Breadboard + 65 Wire Jumper Kit'
    ],
    targetCourse: '1st Year Engineering',
    relevantSemesters: [2],
    status: 'ACTIVE',
    preferredSpotId: 'spot-lib',
    viewsCount: 67,
    savesCount: 18,
    createdAt: '2026-10-07T12:00:00Z',
  },
  {
    id: 'list-arduino-rent',
    sellerId: 'user-priya',
    campusId: 'camp-iitd',
    categoryId: 'cat-elec',
    title: 'Arduino Uno R3 Project Kit (Sensors, Motors, Breadboard, LCD)',
    description: 'Available for semester course project rental. Keep it for your 6-week mini project instead of buying a new ₹1,800 kit.',
    images: [
      'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&q=80&w=600',
    ],
    mode: 'RENT',
    price: 80,
    originalNewPrice: 1800,
    rentalRatePerWeek: 80,
    condition: 'LIKE_NEW',
    targetCourse: 'ECE / CS / Robotics',
    relevantSemesters: [2, 3, 4],
    status: 'ACTIVE',
    preferredSpotId: 'spot-sac',
    viewsCount: 33,
    savesCount: 5,
    createdAt: '2026-10-06T18:40:00Z',
  },
];

export const INITIAL_NEED_REQUESTS: NeedRequest[] = [
  {
    id: 'need-calc-cw',
    buyerId: 'user-amit',
    campusId: 'camp-iitd',
    categoryId: 'cat-calc',
    itemTitle: 'Casio FX-991CW Calculator',
    maxBudget: 850,
    preferredCondition: 'EXCELLENT',
    requiredByDate: '2026-10-15',
    notes: 'Need for upcoming mid-sem differential equation exam. Prefer meeting at Central Library.',
    targetSemester: 2,
    status: 'OPEN',
    createdAt: '2026-10-06T11:00:00Z',
  },
  {
    id: 'need-drafter',
    buyerId: 'user-amit',
    campusId: 'camp-iitd',
    categoryId: 'cat-draw',
    itemTitle: 'Engineering Drawing Drafter & Kit',
    maxBudget: 500,
    preferredCondition: 'GOOD',
    requiredByDate: '2026-10-12',
    notes: 'Urgent for Engineering Graphics practical sheet submissions.',
    targetSemester: 2,
    status: 'OPEN',
    createdAt: '2026-10-05T09:30:00Z',
  },
  {
    id: 'need-korth-dbms',
    buyerId: 'user-priya',
    campusId: 'camp-iitd',
    categoryId: 'cat-books',
    itemTitle: 'Database System Concepts (Silberschatz/Korth)',
    maxBudget: 400,
    preferredCondition: 'GOOD',
    requiredByDate: '2026-10-20',
    notes: 'Semester 4 core CS/IT course book.',
    targetSemester: 4,
    status: 'OPEN',
    createdAt: '2026-10-07T15:20:00Z',
  },
];

export const SEMESTER_STARTER_PACKS_CATALOG: SemesterPackItem[] = [
  {
    name: 'Advanced Engineering Math (Kreyszig)',
    category: 'Textbooks',
    originalPrice: 899,
    resalePrice: 350,
    semester: 2,
    icon: 'BookOpen',
  },
  {
    name: 'Casio Scientific Calculator FX-991CW',
    category: 'Calculators',
    originalPrice: 1595,
    resalePrice: 750,
    semester: 2,
    icon: 'Calculator',
  },
  {
    name: 'Omega Mini Drafter & Board Clips',
    category: 'Drawing Kits',
    originalPrice: 1150,
    resalePrice: 450,
    semester: 2,
    icon: 'DraftingCompass',
  },
  {
    name: 'Chemistry / Workshop White Lab Coat',
    category: 'Lab Coats',
    originalPrice: 450,
    resalePrice: 0, // Free giveaway
    semester: 2,
    icon: 'FlaskConical',
  },
  {
    name: 'Practical Observation & Record File Set',
    category: 'Stationery & Records',
    originalPrice: 180,
    resalePrice: 60,
    semester: 2,
    icon: 'FileText',
  },
];
